### ISSUE TITLE
Key config not working ... perfectly

### ISSUE THREAD

**Issue by Knito58** [irtimaled/BoundingBoxOutlineReloaded#77] opened 2019-12-16 17:22 UTC
Ok it works but not correctly. Not entirely.
If I config the shortcut to be "F9" instead of "b" that works instantly. Yay!

But then after leaving the game and coming back there's the issue:

The control GUI shows "F9". It seems to know about that fact.
But the game reacts as if "b" was configured and shows outlines on hitting "b", taking preference over my other mod which uses "b".

Going to the controls I erase F9 and set F9 freshly.
Then F9 works again until next game start.

Versions:
Forge: 28.1.106
MC: 1.14.4
BBOR: 1.0.14-1.14.4

**Comment by irtimaled** [comment] 2020-05-16 08:10
This is fixed in the next release

**Comment by Knito58** [comment] 2020-06-11 06:56
I'm very sorry to inform you: It still did not work after the next release and I meanwhile solved this by uninstalling this mod.

**Comment by irtimaled** [comment] 2020-06-11 07:03
Odd - I was able to reproduce the issue in the version you mentioned but not in the latest release.

**Comment by irtimaled** [comment] 2020-06-11 07:04
F keys are not normally supported by Minecraft so perhaps this is why they do not persist.

**Comment by irtimaled** [comment] 2020-06-11 07:08
What mod filename do you have loaded?

**Comment by irtimaled** [comment] 2020-06-11 07:09
I wonder if your other mod is conflicting with BBOR - what mod is it?

**Comment by Knito58** [comment] 2020-06-11 14:51
I re-installed it back again to my single player 1.15.2 installation.

Versions:

Forge: 1.15.2-31.2.5
BBOutlineReloaded-2.2-1.15.2-forge
Mod using the "b" - key: Xaero's Minimap. The B-key invokes waypoint creation. I had Xaero's mod a long time before bboutline so if it had been the other way around the error would probably never have been seen.

First start:

bboutline is on "b". Hitting "b" after starting up MC invokes BBOutline, not the waypoint menu.
I configured the key for  BBOutline to be F9. Yay! Both mods work. Xaero opens the waypoint menu with "b", BBOutline does its things on F9.

Shut down Minecraft.

Second start:

Hitting "b" after starting up MC invokes BBOutline, not the waypoint menu. Looking up the config options shows "F9" for BBOutline. Klick on that option, set it again to "F9". (It was on "F9" - visibly - but now it is truly on "F9") Now - and only now! BBOutline reacts to the F9-key and no more to "b". Until next reload.

As I surely reconfigured the F9-key a 100 times there was a time when I said: Enough.

Normally, I'm much quicker kicking mods but BBOutline was right about the relocation of slime junks after a Forge update on my server. Xaero insisted on the old locations, but there were never slimes again. So I really wanted to keep BBOutline but it hurts too much. As I hope now the error becomes finally fixed I will wait a while and keep it installed.

**Comment by irtimaled** [comment] 2020-06-12 17:30
Okay - I was able to reproduce this issue. Looks like forge do something weird when loading the key settings.

**Comment by Knito58** [comment] 2020-06-12 18:37
Good Thing you can reproduce that.

**Comment by irtimaled** [comment] 2020-08-23 19:53
Please try this again in 2.3 release

**Closed by irtimaled** 2020-08-23 19:53 UTC
