### ISSUE TITLE
Server crashes when client connects

### ISSUE THREAD

**Issue by RichyFreeway** [irtimaled/BoundingBoxOutlineReloaded#51] opened 2019-05-02 18:07 UTC
Running BBOR on 1.13.2 carpetmod. Updated to the latest version a few days ago and since then we've had a couple of instances where the server crashes when a client connects. The only times it has happened there has been another player on the server too. This may be coincidence or relevant IDK.

[crash-2019-05-02_12.28.00-server.txt](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/3139362/crash-2019-05-02_12.28.00-server.txt)
[crash-2019-05-01_19.39.53-server.txt](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/3139363/crash-2019-05-01_19.39.53-server.txt)

Crashlogs provided!

Have run most of the previous versions with no problems at all.

**Comment by irtimaled** [comment] 2019-05-13 04:23
I believe this issue is now fixed - I was unable to reproduce so if you can please let me know how you get on with the latest version

**Closed by irtimaled** 2019-05-13 04:23 UTC
