### ISSUE TITLE
Failed to download file

### ISSUE THREAD

**Issue by Mangabum** [irtimaled/BoundingBoxOutlineReloaded#41] opened 2019-02-14 09:21 UTC
Game refuses to launch, instead it throws back an error:-

Failed to download file. bbor-1.0.4-1.13.2.jar
Name: bbor-1.0.4-1.13.2.jar
URL: https://libraries.minecraft.net/com/irtimaled/bbor/1.0.4-1.13.2/bbor-1.0.4-1.13.2.jar
Error details: HTTP 404: Not Found
Filename on disk: 2787-66c5-590d-c8c9
Path: C:\Users\TCK'SP~1\AppData\Local\Temp\2787-66c5-590d-c8c9
Exists: file

Playing vanilla 1.13.2. Only mods used were Optifine. Reinstalling the vanilla bbor version several times does not fix things.

**Comment by irtimaled** [comment] 2019-02-28 06:41
@Mangabum @JTurn01 Could either of you try installing rift 1.13.2 and see if you get the same issue.

**Comment by JTurn01** [comment] 2019-03-01 14:18
@irtimaled The issue is still occuring even after installing Rift. (Version 1.0.4-106) 
I put the rift version into the mods folder and it started but nothing happened in-game.
The vanilla version that installs also still comes up with the same error. 
Let me know if you want any more info.

**Comment by irtimaled** [comment] 2019-03-01 19:49
What's the error you get now?

**Comment by JTurn01** [comment] 2019-03-01 23:47
@irtimaled 
Scratch that, the mod does work with rift.
However, the same issue is occurring with the vanilla version install.

**Comment by irtimaled** [comment] 2019-03-02 04:01
Okay - look's like something on your machine is stopping Minecraft from seeing the file the installer put in your .minecraft/libraries folder.  Not sure what might be causing it but looks like there is a fix that I'll need to work on.

**Comment by Darwign** [comment] 2019-03-02 12:54
same here I cant run it and if I try using forge it doesnt load

**Comment by irtimaled** [comment] 2019-03-03 09:09
@Darwign That's probably because it's not a forge mod. Either vanilla, rift or fabric - Forge is still incomplete.

**Comment by Darwign** [comment] 2019-03-03 11:33
Yea but vanilla doesn't work either

**Comment by TheGnarp** [comment] 2019-03-05 21:32
Same issue with bbor-1.0.5-1.13.2
Still looking forward to using this! ^_^

**Comment by irtimaled** [comment] 2019-03-11 07:30
This is resolved in 1.0.6

**Closed by irtimaled** 2019-03-11 07:30 UTC
