### ISSUE TITLE
crash after loading world

### ISSUE THREAD

**Issue by meglenss** [irtimaled/BoundingBoxOutlineReloaded#40] opened 2019-02-13 21:11 UTC
Upon loading a world the game crashes after a couple seconds of playtime. If the world was created before or after the mod was installed does not affect the outcome.

Error report:

[hs_err_pid8124.log](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/2862226/hs_err_pid8124.log)

**Comment by irtimaled** [comment] 2019-02-14 07:36
Thanks for the report - the error report doesn't indicate any involvement of the mod in the crash. It is possible that the error was indirectly caused by the mod but no idea how to reproduce.

**Comment by meglenss** [comment] 2019-02-14 12:27
does the version of Java matter by any chance?

**Comment by irtimaled** [comment] 2019-02-28 06:43
I honestly don't know the answer to that.  Perhaps if you could try using Java 8 and see if you still get the issue?

**Comment by meglenss** [comment] 2019-03-11 18:33
turns out my intel graphics driver is broken (ig75icd64.dll is corrupted/missing/outdated) and acer doesn't provide an updated version :-/

**Comment by irtimaled** [comment] 2019-03-15 16:25
Sorry to hear that - Hope you get it figured out!

Closing

**Closed by irtimaled** 2019-03-15 16:25 UTC
